namespace DNF.Net.Enums
{
    public enum DnfTimeline
    {
        None = 0,
        CharacterCreate = 101,
        CharacterNameModify = 102,
        CharacterChangeJob = 103,
        CharacterFullLevelAchieve = 104,
        AdventureNameModify = 105,
        Raid = 201,
        TowerOfAnguishConquest = 202,
        TowerOfDespairConquest = 203,
        OldMasuDungeonSuppression = 204,
        EmpireArenaHardClear = 205,
        MasuDungeonSuppression = 206,
        FiendWarClear = 207,
        TowerOfTheDeadConquest = 208,
        LegionClear = 209,
        RaidAdvanceParty = 210,
        PvpExpLevelUp = 301,
        ItemReinforcement = 401,
        ItemAmplification = 402,
        ItemRefinement = 403,
        ItemRemodeling = 404,
        ItemCarving = 405,
        ItemSuccession = 406,
        SealedLockItemGot = 501,
        LegendaryItemGot = 502,
        EchonLegendaryItemGot = 503,
        PotBoxItemGot = 504,
        DungeonDropItemGot = 505,
        ExchangeItemGot = 506,
        RaidCardRewardItemGot = 507,
        ShopItemGot = 508,
        NpcItemTranscendentalTransmission = 509,
        ExchangeItem = 510,
        UpgradeItemGot = 511,
        Authority = 512,
        DungeonCardRewardItemGot = 513,
        RecipeItemGot = 514,
        NpcItemTranscendentalReceipt = 515,
        StoneOfTranscendentalUse = 516,
        ItemFusionSeparation = 517,
        SpecialItemGot = 518,
        ItemConversion = 519,
        EquipmentProductionItemGot = 520,
        RaidAuctionRewardItemGot = 521,
        RuneGot = 601,
        TalismanGot = 602
    }
}
